//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice19
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting
    {
        public int НомерПункта { get; set; }
        public System.DateTime ДатаПеречисления { get; set; }
        public string ОрганизацияПолучатель { get; set; }
        public string Адрес { get; set; }
        public string Коммерческая { get; set; }
        public string ВидЗатратПеречисления { get; set; }
        public int СуммаПеречисления { get; set; }
    }
}
